run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
  errcheck:
    exclude-functions:
      - io.Copy
      - (io.Closer).Close
  gocyclo:
    min-complexity: 25
  goconst:
    min-len: 3
    min-occurrences: 5
  gosec:
    excludes:
      - G101
      - G306

issues:
  exclude-dirs:
    - tools
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gocyclo
        - gosec
        - gosimple

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocyclo
    - goconst
    - gofmt
    - unconvert
    - misspell
    - gosec
