// Package agentsmd compiles an XcaffoldConfig AST into one or more AGENTS.md
// files — a root-level file and optionally directory-scoped files for rules
// with paths: constraints.
package agentsmd

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/saero-ai/xcaffold/internal/ast"
	"github.com/saero-ai/xcaffold/internal/output"
	"github.com/saero-ai/xcaffold/internal/resolver"
)

// warningWriter is the destination for fidelity warnings.
// Overridable in tests to capture output.
var warningWriter io.Writer = os.Stderr

// Renderer compiles an XcaffoldConfig AST into AGENTS.md output files.
type Renderer struct{}

// New returns a new Renderer instance.
func New() *Renderer { return &Renderer{} }

// Target returns the canonical target name for this renderer.
func (r *Renderer) Target() string { return "agentsmd" }

// OutputDir returns the base output directory for this renderer.
// AGENTS.md lives at the repository root, so this returns ".".
func (r *Renderer) OutputDir() string { return "." }

// Render wraps a files map in an output.Output. Identity operation, consistent
// with the Claude renderer.
func (r *Renderer) Render(files map[string]string) *output.Output {
	return &output.Output{Files: files}
}

// Compile translates an XcaffoldConfig AST into AGENTS.md files.
// baseDir is the directory containing scaffold.xcf; used to resolve
// instructions_file: paths. Compile never panics — all errors are returned.
func (r *Renderer) Compile(config *ast.XcaffoldConfig, baseDir string) (*output.Output, error) {
	out := &output.Output{Files: make(map[string]string)}

	// Group rules by directory prefix. Bucket "." = root AGENTS.md.
	ruleGroups := groupRulesByDirectory(config.Rules)

	rootContent, err := buildRootFile(config, baseDir, ruleGroups["."])
	if err != nil {
		return nil, err
	}
	out.Files["AGENTS.md"] = rootContent

	// Emit directory-scoped AGENTS.md files for non-root rule buckets.
	for dir, rules := range ruleGroups {
		if dir == "." {
			continue
		}
		dirContent, err := buildDirFile(rules, baseDir)
		if err != nil {
			return nil, err
		}
		out.Files[filepath.Clean(dir+"/AGENTS.md")] = dirContent
	}

	return out, nil
}

// buildRootFile constructs the root AGENTS.md content.
func buildRootFile(config *ast.XcaffoldConfig, baseDir string, globalRules []namedRule) (string, error) {
	var sb strings.Builder
	sb.WriteString("<!-- Generated by xcaffold. Do not edit manually. -->\n")

	var proj ast.ProjectConfig
	if config.Project != nil {
		proj = *config.Project
	}
	if err := renderProjectSection(&sb, proj); err != nil {
		return "", err
	}
	if err := renderAgentsSection(&sb, config.Agents, baseDir); err != nil {
		return "", err
	}
	if err := renderSkillsSection(&sb, config.Skills, baseDir); err != nil {
		return "", err
	}
	if err := renderRulesSection(&sb, globalRules, baseDir); err != nil {
		return "", err
	}
	if err := renderWorkflowsSection(&sb, config.Workflows, baseDir); err != nil {
		return "", err
	}

	return sb.String(), nil
}

// buildDirFile constructs a directory-scoped AGENTS.md containing only rules.
func buildDirFile(rules []namedRule, baseDir string) (string, error) {
	var sb strings.Builder
	sb.WriteString("<!-- Generated by xcaffold. Do not edit manually. -->\n")

	if err := renderRulesSection(&sb, rules, baseDir); err != nil {
		return "", err
	}

	return sb.String(), nil
}

// renderProjectSection emits the ## Project section when name or description is set.
func renderProjectSection(sb *strings.Builder, p ast.ProjectConfig) error {
	if p.Name == "" && p.Description == "" {
		return nil
	}
	sb.WriteString("\n## Project\n\n")
	sb.WriteString(p.Name)
	if p.Description != "" {
		sb.WriteString(" — ")
		sb.WriteString(p.Description)
	}
	sb.WriteString("\n")
	return nil
}

// renderAgentsSection emits the ## Agents section for all agents in the config.
func renderAgentsSection(sb *strings.Builder, agents map[string]ast.AgentConfig, baseDir string) error {
	if len(agents) == 0 {
		return nil
	}
	sb.WriteString("\n## Agents\n")
	for id, agent := range agents {
		suppress := isSuppressed(agent)
		if !suppress {
			warnLossyAgent(id, agent)
		}

		fmt.Fprintf(sb, "\n### %s\n", id)
		if agent.Model != "" {
			fmt.Fprintf(sb, "**Model**: %s\n", agent.Model)
		}
		if agent.Description != "" {
			fmt.Fprintf(sb, "**Description**: %s\n", agent.Description)
		}

		body, err := resolver.ResolveInstructions(agent.Instructions, agent.InstructionsFile, "", baseDir)
		if err != nil {
			return fmt.Errorf("failed to resolve instructions for agent %q: %w", id, err)
		}
		if body != "" {
			sb.WriteString("\n")
			sb.WriteString(strings.TrimRight(body, "\n"))
			sb.WriteString("\n")
		}
	}
	return nil
}

// renderSkillsSection emits the ## Skills section for all skills in the config.
func renderSkillsSection(sb *strings.Builder, skills map[string]ast.SkillConfig, baseDir string) error {
	if len(skills) == 0 {
		return nil
	}
	sb.WriteString("\n## Skills\n")
	for id, skill := range skills {
		warnLossySkill(id, skill)

		fmt.Fprintf(sb, "\n### %s\n", id)
		if skill.Description != "" {
			fmt.Fprintf(sb, "**Description**: %s\n", skill.Description)
		}

		body, err := resolver.ResolveInstructions(skill.Instructions, skill.InstructionsFile, "", baseDir)
		if err != nil {
			return fmt.Errorf("failed to resolve instructions for skill %q: %w", id, err)
		}
		if body != "" {
			sb.WriteString("\n")
			sb.WriteString(strings.TrimRight(body, "\n"))
			sb.WriteString("\n")
		}
	}
	return nil
}

// renderRulesSection emits the ## Rules section for the given named rules.
func renderRulesSection(sb *strings.Builder, rules []namedRule, baseDir string) error {
	if len(rules) == 0 {
		return nil
	}
	sb.WriteString("\n## Rules\n")
	for _, nr := range rules {
		warnLossyRule(nr.id, nr.rule)

		fmt.Fprintf(sb, "\n### %s\n", nr.id)
		if len(nr.rule.Paths) > 0 {
			fmt.Fprintf(sb, "**Applies to**: %s\n", strings.Join(nr.rule.Paths, ", "))
		} else {
			sb.WriteString("**Applies to**: all files\n")
		}

		body, err := resolver.ResolveInstructions(nr.rule.Instructions, nr.rule.InstructionsFile, "", baseDir)
		if err != nil {
			return fmt.Errorf("failed to resolve instructions for rule %q: %w", nr.id, err)
		}
		if body != "" {
			sb.WriteString("\n")
			sb.WriteString(strings.TrimRight(body, "\n"))
			sb.WriteString("\n")
		}
	}
	return nil
}

// renderWorkflowsSection emits the ## Workflows section for all workflows.
func renderWorkflowsSection(sb *strings.Builder, workflows map[string]ast.WorkflowConfig, baseDir string) error {
	if len(workflows) == 0 {
		return nil
	}
	sb.WriteString("\n## Workflows\n")
	for id, wf := range workflows {
		fmt.Fprintf(sb, "\n### %s\n", id)
		if wf.Description != "" {
			fmt.Fprintf(sb, "**Description**: %s\n", wf.Description)
		}

		body, err := resolver.ResolveInstructions(wf.Instructions, wf.InstructionsFile, "", baseDir)
		if err != nil {
			return fmt.Errorf("failed to resolve instructions for workflow %q: %w", id, err)
		}
		if body != "" {
			sb.WriteString("\n")
			sb.WriteString(strings.TrimRight(body, "\n"))
			sb.WriteString("\n")
		}
	}
	return nil
}

// namedRule pairs a rule config with its map key (the rule ID).
type namedRule struct {
	id   string
	rule ast.RuleConfig
}

// groupRulesByDirectory splits rules into buckets keyed by their common directory
// prefix. Key "." means the root AGENTS.md. Rules with no paths or with a global
// prefix (empty / ".") also land in the "." bucket.
func groupRulesByDirectory(rules map[string]ast.RuleConfig) map[string][]namedRule {
	groups := map[string][]namedRule{
		".": {},
	}

	for id, rule := range rules {
		if len(rule.Paths) == 0 {
			groups["."] = append(groups["."], namedRule{id: id, rule: rule})
			continue
		}

		prefix := commonDirPrefix(rule.Paths)
		if prefix == "" || prefix == "." {
			groups["."] = append(groups["."], namedRule{id: id, rule: rule})
		} else {
			groups[prefix] = append(groups[prefix], namedRule{id: id, rule: rule})
		}
	}

	return groups
}

// commonDirPrefix extracts the longest common directory prefix from a set of
// glob patterns. It splits each pattern on "/" and considers only the directory
// components (all path segments except the last). The result is the common
// prefix of those component slices joined with "/".
func commonDirPrefix(patterns []string) string {
	if len(patterns) == 0 {
		return ""
	}

	// Compute directory components for each pattern.
	dirParts := make([][]string, 0, len(patterns))
	for _, p := range patterns {
		parts := strings.Split(p, "/")
		// Drop the last component (filename/glob part), keep only dir segments.
		dirs := parts[:len(parts)-1]
		// Filter out glob characters in the leading segments — if any dir segment
		// contains "*" or "?", it's a global pattern and we stop there.
		cleaned := make([]string, 0, len(dirs))
		for _, d := range dirs {
			if strings.ContainsAny(d, "*?[") {
				break
			}
			cleaned = append(cleaned, d)
		}
		dirParts = append(dirParts, cleaned)
	}

	if len(dirParts) == 0 || len(dirParts[0]) == 0 {
		return ""
	}

	// Find common prefix across all patterns' dir parts.
	prefix := dirParts[0]
	for _, parts := range dirParts[1:] {
		prefix = commonPrefix(prefix, parts)
	}

	if len(prefix) == 0 {
		return ""
	}

	return strings.Join(prefix, "/")
}

// commonPrefix returns the longest common prefix of two string slices.
func commonPrefix(a, b []string) []string {
	max := len(a)
	if len(b) < max {
		max = len(b)
	}
	for i := 0; i < max; i++ {
		if a[i] != b[i] {
			return a[:i]
		}
	}
	return a[:max]
}

// isSuppressed returns true if the agent has SuppressFidelityWarnings set for
// the "agentsmd" target.
func isSuppressed(agent ast.AgentConfig) bool {
	if override, ok := agent.Targets["agentsmd"]; ok {
		return override.SuppressFidelityWarnings != nil && *override.SuppressFidelityWarnings
	}
	return false
}

// warnLossy emits one fidelity warning line to warningWriter.
func warnLossy(kind, field, id string) {
	fmt.Fprintf(warningWriter, "WARNING (agentsmd): field %q on %s %q has no AGENTS.md equivalent and was dropped.\n", field, kind, id)
}

// warnLossyAgent emits fidelity warnings for lossy AgentConfig fields.
//
//nolint:gocyclo
func warnLossyAgent(id string, a ast.AgentConfig) {
	if len(a.Tools) > 0 {
		warnLossy("agent", "tools", id)
	}
	if len(a.DisallowedTools) > 0 {
		warnLossy("agent", "disallowedTools", id)
	}
	if len(a.Skills) > 0 {
		warnLossy("agent", "skills", id)
	}
	if len(a.Rules) > 0 {
		warnLossy("agent", "rules", id)
	}
	if a.Effort != "" {
		warnLossy("agent", "effort", id)
	}
	if a.PermissionMode != "" {
		warnLossy("agent", "permissionMode", id)
	}
	if a.Isolation != "" {
		warnLossy("agent", "isolation", id)
	}
	if a.Color != "" {
		warnLossy("agent", "color", id)
	}
	if a.MaxTurns > 0 {
		warnLossy("agent", "maxTurns", id)
	}
	if a.Background != nil {
		warnLossy("agent", "background", id)
	}
	if a.Readonly != nil {
		warnLossy("agent", "readonly", id)
	}
	if a.Mode != "" {
		warnLossy("agent", "mode", id)
	}
	if a.When != "" {
		warnLossy("agent", "when", id)
	}
	if a.InitialPrompt != "" {
		warnLossy("agent", "initialPrompt", id)
	}
	if a.Memory != "" {
		warnLossy("agent", "memory", id)
	}
	if len(a.Hooks) > 0 {
		warnLossy("agent", "hooks", id)
	}
	if len(a.MCPServers) > 0 {
		warnLossy("agent", "mcpServers", id)
	}
	if len(a.Targets) > 0 {
		warnLossy("agent", "targets", id)
	}
	if len(a.Assertions) > 0 {
		warnLossy("agent", "assertions", id)
	}
	if len(a.MCP) > 0 {
		warnLossy("agent", "mcp", id)
	}
}

// warnLossySkill emits fidelity warnings for lossy SkillConfig fields.
func warnLossySkill(id string, s ast.SkillConfig) {
	if len(s.Tools) > 0 {
		warnLossy("skill", "tools", id)
	}
	if len(s.References) > 0 {
		warnLossy("skill", "references", id)
	}
	if len(s.Scripts) > 0 {
		warnLossy("skill", "scripts", id)
	}
	if len(s.Assets) > 0 {
		warnLossy("skill", "assets", id)
	}
}

// warnLossyRule emits fidelity warnings for lossy RuleConfig fields.
func warnLossyRule(id string, rule ast.RuleConfig) {
	if rule.AlwaysApply != nil {
		warnLossy("rule", "alwaysApply", id)
	}
}
