// Code generated by gen-schema; DO NOT EDIT.

package renderer

import "github.com/saero-ai/xcaffold/internal/ast"

func ExtractAgentPresentFields(a ast.AgentConfig) map[string]string {
	m := make(map[string]string)
	if a.Name != "" {
		m["name"] = a.Name
	}
	if a.Description != "" {
		m["description"] = a.Description
	}
	if a.Model != "" {
		m["model"] = a.Model
	}
	if a.Effort != "" {
		m["effort"] = a.Effort
	}
	if a.MaxTurns != 0 {
		m["max-turns"] = "set"
	}
	if len(a.Tools.Values) > 0 {
		m["tools"] = "set"
	}
	if len(a.DisallowedTools.Values) > 0 {
		m["disallowed-tools"] = "set"
	}
	if a.Readonly != nil {
		m["readonly"] = "set"
	}
	if a.PermissionMode != "" {
		m["permission-mode"] = a.PermissionMode
	}
	if a.DisableModelInvocation != nil {
		m["disable-model-invocation"] = "set"
	}
	if a.UserInvocable != nil {
		m["user-invocable"] = "set"
	}
	if a.Background != nil {
		m["background"] = "set"
	}
	if a.Isolation != "" {
		m["isolation"] = a.Isolation
	}
	if len(a.Memory) > 0 {
		m["memory"] = "set"
	}
	if a.Color != "" {
		m["color"] = a.Color
	}
	if a.InitialPrompt != "" {
		m["initial-prompt"] = a.InitialPrompt
	}
	if len(a.Skills.Values) > 0 {
		m["skills"] = "set"
	}
	if len(a.Rules.Values) > 0 {
		m["rules"] = "set"
	}
	if len(a.MCP.Values) > 0 {
		m["mcp"] = "set"
	}
	if len(a.Assertions.Values) > 0 {
		m["assertions"] = "set"
	}
	if len(a.MCPServers) > 0 {
		m["mcp-servers"] = "set"
	}
	if len(a.Hooks) > 0 {
		m["hooks"] = "set"
	}
	if len(a.Targets) > 0 {
		m["targets"] = "set"
	}
	if a.Body != "" {
		m["body"] = "set"
	}
	return m
}

func ExtractSkillPresentFields(s ast.SkillConfig) map[string]string {
	m := make(map[string]string)
	if s.Name != "" {
		m["name"] = s.Name
	}
	if s.Description != "" {
		m["description"] = s.Description
	}
	if s.WhenToUse != "" {
		m["when-to-use"] = s.WhenToUse
	}
	if s.License != "" {
		m["license"] = s.License
	}
	if len(s.AllowedTools.Values) > 0 {
		m["allowed-tools"] = "set"
	}
	if s.DisableModelInvocation != nil {
		m["disable-model-invocation"] = "set"
	}
	if s.UserInvocable != nil {
		m["user-invocable"] = "set"
	}
	if s.ArgumentHint != "" {
		m["argument-hint"] = s.ArgumentHint
	}
	if len(s.Artifacts) > 0 {
		m["artifacts"] = "set"
	}
	if len(s.Targets) > 0 {
		m["targets"] = "set"
	}
	if s.Body != "" {
		m["body"] = "set"
	}
	return m
}

func ExtractRulePresentFields(r ast.RuleConfig) map[string]string {
	m := make(map[string]string)
	if r.AlwaysApply != nil {
		m["always-apply"] = "set"
	}
	if r.Description != "" {
		m["description"] = r.Description
	}
	if r.Activation != "" {
		m["activation"] = r.Activation
	}
	if r.Name != "" {
		m["name"] = r.Name
	}
	if len(r.Paths.Values) > 0 {
		m["paths"] = "set"
	}
	if len(r.ExcludeAgents.Values) > 0 {
		m["exclude-agents"] = "set"
	}
	if len(r.Targets) > 0 {
		m["targets"] = "set"
	}
	if r.Body != "" {
		m["body"] = "set"
	}
	return m
}
