package templates

import (
	"strings"
)

// fence is the markdown code fence delimiter.
const fence = "```"

func padField(s string) string {
	const width = 22
	if len(s) >= width {
		return s
	}
	return s + strings.Repeat(" ", width-len(s))
}

// RenderXcaffoldSkillXCF generates the xcf/skills/xcaffold/xcaffold.xcf content.
// The output uses frontmatter format: YAML metadata between --- delimiters, then plain markdown body.
func RenderXcaffoldSkillXCF(targets []string) string {
	lines := []string{
		"---",
		"# kind: skill - provider field support for your selected targets",
		"#",
		"#  Field                 " + strings.Join(targets, "  "),
	}

	for _, field := range []string{"name / description", "allowed-tools", "instructions"} {
		lines = append(lines, "#  "+padField(field)+strings.Repeat("YES      ", len(targets)))
	}

	lines = append(lines, "",
		"kind: skill",
		`version: "1.0"`,
		"name: xcaffold",
		`description: >-`,
		`  Scaffolds, compiles, and validates AI agent configurations using xcaffold — the`,
		`  deterministic agent configuration compiler. Invoke when the user asks to create agents,`,
		`  skills, rules, or policies; when they want to target Claude Code, Cursor, Gemini CLI,`,
		`  GitHub Copilot, or Antigravity; when setting up a new xcaffold project; or when`,
		`  validating or applying existing xcf configurations.`,
		"allowed-tools: [Bash, Read, Edit, Glob, Grep]",
		"references:",
		"  - .xcaffold/schemas/agent.xcf.reference",
		"  - .xcaffold/schemas/skill.xcf.reference",
		"  - .xcaffold/schemas/rule.xcf.reference",
		"  - .xcaffold/schemas/workflow.xcf.reference",
		"  - .xcaffold/schemas/mcp.xcf.reference",
		"  - .xcaffold/schemas/hooks.xcf.reference",
		"  - .xcaffold/schemas/memory.xcf.reference",
		"  - .xcaffold/schemas/cli-cheatsheet.reference",
		"---",
		"# xcaffold — Agent Configuration Compiler",
		"",
		"xcaffold compiles `.xcf` YAML source files into native AI coding agent configurations",
		"for Claude Code, Cursor, Gemini CLI, GitHub Copilot, and Antigravity. It is the",
		"determinism layer between human (or AI) authoring and provider output — preventing",
		"hallucinated field names, incorrect directory structures, and unsupported frontmatter.",
		"",
		"## When to use this skill",
		"",
		"Use xcaffold when:",
		"- The user asks to create or configure an agent, skill, rule, workflow, or MCP server",
		"- The user wants to target multiple AI providers from a single xcf source",
		`- The user says "scaffold", "initialize", or "set up xcaffold"`,
		"- You need to validate or compile agent configs for a provider",
		"- The user asks to import existing provider configs (.claude/, .cursor/, etc.) into xcaffold",
		`- The user asks "what providers support X field?"`,
		"",
		"## Critical rules",
		"",
		"1. **Never write directly to `.claude/`, `.cursor/`, `.gemini/`, `.github/`, or `.agents/`.**",
		"   Those directories are xcaffold output — owned by `xcaffold apply`. Always edit `xcf/` files.",
		"",
		"2. **Always run `xcaffold validate` before `xcaffold apply`.**",
		"   Policy violations are caught before any files are written.",
		"",
		"3. **Read the companion references before setting fields.**",
		"   All 8 reference files in `.xcaffold/schemas/` are the",
		"   ground-truth field catalogs for your selected providers.",
		"",
		"4. **Respect the provider matrix comment at the top of each `.xcf` file.**",
		"   Fields marked 'dropped' for a target will be silently removed at compile time. Leave",
		"   them in source — xcaffold manages the drop.",
		"",
		"---",
		"",
		"## Operating guide",
		"",
		"### Starting a new project",
		"",
		fence+"bash",
		"# Interactive — prompts for providers, generates Xaff authoring toolkit",
		"xcaffold init",
		"",
		"# Non-interactive — explicit targets, machine-readable manifest",
		"xcaffold init --target claude,cursor --yes --json",
		fence,
		"",
		"The `--json` flag emits a machine-readable manifest of all generated files.",
		"",
		"Generated layout:",
		"",
		fence,
		"my-project/",
		"  .xcaffold/",
		"    project.xcf              # kind: project (targets, resource refs)",
		"    schemas/",
		"      agent.xcf.reference    # annotated agent field catalog",
		"      skill.xcf.reference    # annotated skill field catalog",
		"      rule.xcf.reference     # annotated rule field catalog",
		"      workflow.xcf.reference # annotated workflow field catalog",
		"      mcp.xcf.reference      # annotated MCP field catalog",
		"      hooks.xcf.reference    # annotated hooks field catalog",
		"      memory.xcf.reference   # annotated memory field catalog",
		"      cli-cheatsheet.reference  # CLI command reference",
		"  xcf/",
		"    agents/",
		"      xaff/",
		"        agent.xcf            # base Xaff agent (universal)",
		"        agent.claude.xcf     # per-provider override",
		"    skills/",
		"      xcaffold/",
		"        xcaffold.xcf         # THIS SKILL",
		"    rules/",
		"      xcf-conventions/",
		"        xcf-conventions.xcf  # xcaffold authoring conventions",
		"    policies/",
		"      require-agent-description.xcf",
		"      require-agent-instructions.xcf",
		"    settings.xcf             # kind: settings (MCP, permissions)",
		fence,
		"",
		"### Checking compilation state",
		"",
		fence+"bash",
		"xcaffold status              # show drift across all providers",
		"xcaffold status --target claude  # focus on one provider",
		fence,
		"",
		"### Importing existing provider config",
		"",
		fence+"bash",
		"xcaffold import --plan       # preview what will be imported",
		"xcaffold import              # write to xcf/",
		"xcaffold validate            # verify the imported config",
		"xcaffold apply --dry-run     # preview compiled output",
		fence,
		"",
		"---",
		"",
		"## Authoring guide",
		"",
		"### Adding a resource",
		"",
		"1. Read the reference for the resource kind:",
		"",
		fence+"bash",
		"cat .xcaffold/schemas/agent.xcf.reference",
		"cat .xcaffold/schemas/rule.xcf.reference",
		fence,
		"",
		"2. Create the `.xcf` file in the correct directory:",
		"",
		fence+"yaml",
		"# xcf/agents/reviewer/reviewer.xcf",
		"kind: agent",
		`version: "1.0"`,
		"name: reviewer",
		`description: "Code reviewer. Reads code and provides structured feedback."`,
		"tools: [Read, Glob, Grep]",
		"---",
		"You are a code reviewer. Provide actionable feedback.",
		"Focus on correctness, clarity, and security. Do not write files.",
		fence,
		"",
		"3. Resources are discovered automatically — no registration needed.",
		"   xcaffold finds all `.xcf` files under `xcf/` at compile time.",
		"",
		"4. Validate and apply:",
		"",
		fence+"bash",
		"xcaffold validate",
		"xcaffold apply --target claude",
		fence,
		"",
		"### xcf schema quick reference",
		"",
		fence+"yaml",
		"# kind: project — .xcaffold/project.xcf",
		"kind: project",
		`version: "1.0"`,
		`name: "my-project"`,
		"targets:",
		"  - claude",
		"  - cursor",
		"",
		"---",
		"# kind: agent — xcf/agents/<name>/<name>.xcf",
		"kind: agent",
		`version: "1.0"`,
		"name: developer",
		`description: "Required. Short description."`,
		`model: "claude-sonnet-4-6"   # claude, gemini, antigravity only`,
		`effort: "high"               # claude only`,
		"tools: [Read, Write, Edit, Bash]",
		"---",
		"Your agent instructions here. Minimum 10 characters.",
		"",
		"---",
		"# kind: skill — xcf/skills/<name>/<name>.xcf",
		"kind: skill",
		`version: "1.0"`,
		"name: tdd",
		`description: "Guides test-driven development."`,
		"allowed-tools: [Read, Write, Edit, Bash]",
		"---",
		"Write a failing test first. Write minimal code to pass. Refactor.",
		"",
		"---",
		"# kind: rule — xcf/rules/<name>/<name>.xcf",
		"kind: rule",
		`version: "1.0"`,
		"name: my-rule",
		`description: "What this rule enforces."`,
		"activation: always",
		"---",
		"Rule instructions injected into agent context when active.",
		"",
		"---",
		"# kind: workflow — xcf/workflows/<name>/<name>.xcf",
		"kind: workflow",
		`version: "1.0"`,
		"name: my-workflow",
		"steps:",
		"  - name: step-one",
		"    description: First step.",
		"",
		"---",
		"# kind: mcp — xcf/mcp/<name>/<name>.xcf (no body, no targets)",
		"kind: mcp",
		`version: "1.0"`,
		"name: filesystem",
		"type: stdio",
		"command: npx",
		`args: ["-y", "@modelcontextprotocol/server-filesystem", "."]`,
		"",
		"---",
		"# kind: hooks — xcf/hooks/<name>/hooks.xcf (pure YAML, no --- delimiters)",
		"kind: hooks",
		`version: "1.0"`,
		"events:",
		"  PreToolUse:",
		"    - matcher: Bash",
		"      hooks:",
		"        - type: command",
		`          command: "validate.sh"`,
		"",
		"---",
		"# kind: memory — xcf/agents/<agent>/memory/<id>.md",
		"kind: memory",
		`version: "1.0"`,
		"name: project-context",
		"---",
		"Memory content goes here. Discovered by compiler from .md file body.",
		fence,
		"",
		"---",
		"",
		"## Field support matrix (cross-provider)",
		"",
		"| Field | claude | cursor | gemini | copilot | antigravity |",
		"|---|---|---|---|---|---|",
		"| `description` | YES | YES | YES | YES | YES |",
		"| `instructions` | YES | YES | YES | YES | YES |",
		"| `allowed-tools` | YES | YES | YES | YES | YES |",
		"| `model` | YES | dropped | YES | dropped | YES |",
		"| `effort` | YES | dropped | dropped | dropped | dropped |",
		"| `permission-mode` | YES | dropped | dropped | dropped | dropped |",
		"| `hooks` | YES | dropped | dropped | dropped | dropped |",
		"| `memory` | YES | dropped | dropped | dropped | dropped |",
		"",
		"Fields marked 'dropped' remain in `xcf/` source. xcaffold removes them at compile time.",
		"",
		"---",
		"",
		"## Common validation errors",
		"",
		"| Error | Cause | Fix |",
		"|---|---|---|",
		"| `require-agent-instructions` | `instructions:` < 10 chars | Add meaningful instructions |",
		"| `require-agent-description` | `description:` missing | Add a description field |",
		"| `duplicate agent ID` | Same `name:` in two `.xcf` files | Rename one |",
		"| `path traversal` | `instructions-file:` with `..` | Use path relative to project root |",
		"",
		"---",
		"",
		"## CLI reference",
		"",
		"| Command | Purpose |",
		"|---|---|",
		"| `xcaffold init` | Bootstrap new project with xcf/ layout |",
		"| `xcaffold init --target <t> --yes` | Non-interactive init |",
		"| `xcaffold init --json` | Machine-readable manifest |",
		"| `xcaffold apply --target <t>` | Compile xcf/ to provider output |",
		"| `xcaffold apply --dry-run` | Preview output without writing |",
		"| `xcaffold validate` | Schema + policy validation |",
		"| `xcaffold status` | Detect drift in compiled output |",
		"| `xcaffold import` | Import existing provider config |",
		"| `xcaffold graph` | Visualize agent topology |",
	)

	return strings.Join(lines, "\n") + "\n"
}
