package templates

import (
	"strings"
)

// fence is the markdown code fence delimiter.
const fence = "```"

func padField(s string) string {
	const width = 22
	if len(s) >= width {
		return s
	}
	return s + strings.Repeat(" ", width-len(s))
}

// RenderXcaffoldSkillXCF generates the natively structured .xcf file for the xcaffold skill.
// The raw markdown contents are embedded within the 'instructions:' YAML block.
func RenderXcaffoldSkillXCF(targets []string) string {
	lines := []string{
		"# kind: skill - provider field support for your selected targets",
		"#",
		"#  Field                 " + strings.Join(targets, "  "),
	}

	for _, field := range []string{"name / description", "allowed-tools", "instructions"} {
		lines = append(lines, "#  "+padField(field)+strings.Repeat("YES      ", len(targets)))
	}

	lines = append(lines, "",
		"kind: skill",
		`version: "1.0"`,
		"name: xcaffold",
		`description: >-`,
		`  Scaffolds, compiles, and validates AI agent configurations using xcaffold — the`,
		`  deterministic agent config compiler. Invoke when the user asks to create agents,`,
		`  skills, rules, or policies; when they want to target Claude Code, Cursor, Gemini CLI,`,
		`  GitHub Copilot, or Antigravity; when setting up a new xcaffold project; or when`,
		`  validating or applying existing xcf configurations.`,
		"allowed-tools: [Bash, Read, Edit, Glob, Grep]",
		"references:",
		"  - xcf/skills/xcaffold/references/agent.xcf.reference",
		"  - xcf/skills/xcaffold/references/skill.xcf.reference",
		"instructions: |",
		"  # xcaffold — Agent Configuration Compiler",
		"  ",
		"  xcaffold compiles `.xcf` YAML source files into native AI coding agent configurations",
		"  for Claude Code, Cursor, Gemini CLI, GitHub Copilot, and Antigravity. It is the",
		"  determinism layer between human (or AI) authoring and provider output — preventing",
		"  hallucinated field names, incorrect directory structures, and unsupported frontmatter.",
		"  ",
		"  ## When to use this skill",
		"  ",
		"  Use xcaffold when:",
		"  - The user asks to create or configure an agent, skill, rule, or policy",
		"  - The user wants to target multiple AI providers from a single xcf source",
		`  - The user says "scaffold", "initialize", or "set up xcaffold"`,
		"  - You need to validate or compile agent configs for a provider",
		"  - The user asks to import existing provider configs (.claude/, .cursor/, etc.) into xcaffold",
		`  - The user asks "what providers support X field?"`,
		"  ",
		"  ## ⚠️ Critical rules",
		"  ",
		"  1. **Never write directly to `.claude/`, `.cursor/`, `.gemini/`, `.github/`, or `.agents/`.**",
		"     Those directories are xcaffold output — owned by `xcaffold apply`. Always edit `xcf/` files.",
		"  ",
		"  2. **Always run `xcaffold validate` before `xcaffold apply`.**",
		"     Policy violations are caught before any files are written.",
		"  ",
		"  3. **Read the companion references before setting fields.**",
		"     `xcf/skills/xcaffold/references/agent.xcf.reference` and",
		"     `xcf/skills/xcaffold/references/skill.xcf.reference` are the",
		"     ground-truth field catalogs for your selected providers.",
		"  ",
		"  4. **Respect the provider matrix comment at the top of each `.xcf` file.**",
		"     Fields marked 'dropped' for a target will be silently removed at compile time. Leave",
		"     them in source — xcaffold manages the drop.",
		"  ",
		"  ---",
		"  ",
		"  ## Workflow: starting a new project",
		"  ",
		"  "+fence+"bash",
		"  # Interactive — prompts for providers, installs /xcaffold skill",
		"  xcaffold init",
		"  ",
		"  # Non-interactive — explicit targets, machine-readable manifest",
		"  xcaffold init --target claude,cursor --yes --json",
		"  "+fence,
		"  ",
		"  The `--json` flag emits a machine-readable manifest of all generated files.",
		"  ",
		"  Generated layout:",
		"  ",
		"  "+fence,
		"  my-project/",
		"    project.xcf              <- kind: project (targets, resource refs)",
		"    xcf/",
		"      agents/",
		"        developer.xcf         <- kind: agent (with provider matrix)",
		"      skills/",
		"        xcaffold.xcf          <- THIS SKILL",
		"        xcaffold/",
		"          references/",
		"            agent.xcf.reference   <- annotated agent field catalog",
		"            skill.xcf.reference   <- annotated skill field catalog",
		"      rules/",
		"        conventions.xcf       <- kind: rule",
		"      policies/",
		"        safety.xcf            <- kind: policy (guardrails)",
		"      settings.xcf            <- kind: settings (MCP, permissions)",
		"  "+fence,
		"  ",
		"  ---",
		"  ",
		"  ## Workflow: adding a resource",
		"  ",
		"  1. Read the reference for the resource kind:",
		"  ",
		"  "+fence+"bash",
		"  cat xcf/skills/xcaffold/references/agent.xcf.reference",
		"  cat xcf/skills/xcaffold/references/skill.xcf.reference",
		"  "+fence,
		"  ",
		"  2. Create or edit the `.xcf` file:",
		"  ",
		"  "+fence+"yaml",
		"  # xcf/agents/reviewer.xcf",
		"  kind: agent",
		`  version: "1.0"`,
		"  name: reviewer",
		`  description: "Code reviewer agent. Reads code and provides structured feedback."`,
		"  tools: [Read, Glob, Grep]",
		"  instructions: |",
		"    You are a code reviewer. Provide actionable feedback.",
		"    Focus on correctness, clarity, and security. Do not write files.",
		"  "+fence,
		"  ",
		"  3. Register the resource in `project.xcf`:",
		"  ",
		"  "+fence+"yaml",
		"  agents:",
		"    - developer",
		"    - reviewer   # add here",
		"  "+fence,
		"  ",
		"  4. Validate and apply:",
		"  ",
		"  "+fence+"bash",
		"  xcaffold validate",
		"  xcaffold apply --target claude",
		"  "+fence,
		"  ",
		"  ---",
		"  ",
		"  ## Workflow: importing existing provider config",
		"  ",
		"  "+fence+"bash",
		"  xcaffold import --from claude --plan   # preview what will be imported",
		"  xcaffold import --from claude          # write to xcf/",
		"  xcaffold validate                      # verify the imported config",
		"  xcaffold apply --target claude --dry-run",
		"  "+fence,
		"  ",
		"  ---",
		"  ",
		"  ## xcf schema quick reference",
		"  ",
		"  "+fence+"yaml",
		"  # kind: project — project.xcf at project root",
		"  kind: project",
		`  version: "1.0"`,
		`  name: "my-project"`,
		"  targets:",
		"    - claude",
		"    - cursor",
		"  agents:",
		"    - developer",
		"  skills:",
		"    - xcaffold",
		"  rules:",
		"    - conventions",
		"  ",
		"  ---",
		"  # kind: agent — xcf/agents/<name>.xcf",
		"  kind: agent",
		`  version: "1.0"`,
		"  name: developer",
		`  description: "Required. Short description."`,
		`  model: "claude-sonnet-4-6"   # claude, gemini, antigravity only`,
		`  effort: "high"               # claude only`,
		"  tools: [Read, Write, Edit, Bash]",
		"  instructions: |             # Required. Min 10 characters.",
		"    Your agent instructions here.",
		"  ",
		"  ---",
		"  # kind: skill — xcf/skills/<name>.xcf",
		"  kind: skill",
		`  version: "1.0"`,
		"  name: tdd",
		`  description: "Guides test-driven development using red-green-refactor."`,
		"  allowed-tools: [Read, Write, Edit, Bash]",
		"  instructions: |",
		"    Write a failing test first. Write minimal code to pass. Refactor.",
		"  ",
		"  ---",
		"  # kind: policy — xcf/policies/<name>.xcf",
		"  kind: policy",
		`  version: "1.0"`,
		"  name: require-agent-description",
		"  severity: warning",
		"  target: agent",
		"  require:",
		"    - field: description",
		"      is-present: true",
		"  "+fence,
		"  ",
		"  ---",
		"  ",
		"  ## Field support matrix (cross-provider)",
		"  ",
		"  | Field | claude | cursor | gemini | copilot | antigravity |",
		"  |---|---|---|---|---|---|",
		"  | `description` | YES | YES | YES | YES | YES |",
		"  | `instructions` | YES | YES | YES | YES | YES |",
		"  | `allowed-tools` | YES | YES | YES | YES | YES |",
		"  | `model` | YES | dropped | YES | dropped | YES |",
		"  | `effort` | YES | dropped | dropped | dropped | dropped |",
		"  | `permission-mode` | YES | dropped | dropped | dropped | dropped |",
		"  | `hooks` | YES | dropped | dropped | dropped | dropped |",
		"  | `memory` | YES | dropped | dropped | dropped | dropped |",
		"  ",
		"  Fields marked 'dropped' remain in `xcf/` source. xcaffold removes them at compile time.",
		"  ",
		"  ---",
		"  ",
		"  ## Common validation errors",
		"  ",
		"  | Error | Cause | Fix |",
		"  |---|---|---|",
		"  | `require-agent-instructions` | `instructions:` < 10 chars | Add meaningful instructions |",
		"  | `require-agent-description` | `description:` missing | Add a description field |",
		"  | `duplicate agent ID` | Same `name:` in two `.xcf` files | Rename one |",
		"  | `path traversal` | `instructions-file:` with `..` | Use path relative to project root |",
		"  ",
		"  ---",
		"  ",
		"  ## CLI reference",
		"  ",
		"  | Command | Purpose |",
		"  |---|---|",
		"  | `xcaffold init` | Bootstrap new project with xcf/ layout |",
		"  | `xcaffold init --target <t> --yes` | Non-interactive init |",
		"  | `xcaffold init --json` | Machine-readable manifest |",
		"  | `xcaffold apply --target <t>` | Compile xcf/ to provider output |",
		"  | `xcaffold apply --dry-run` | Preview output without writing |",
		"  | `xcaffold validate` | Schema + policy validation |",
		"  | `xcaffold diff` | Detect drift in compiled output |",
		"  | `xcaffold import --from <provider>` | Import existing provider config |",
		"  | `xcaffold graph` | Visualize agent topology |",
		"  | `xcaffold apply --global` | Compiles global.xcf globally |",
		"  ",
		"  Full docs: https://github.com/saero-ai/xcaffold",
	)

	return strings.Join(lines, "\n") + "\n"
}
