package templates

import (
	"fmt"
	"strings"
)

// Template defines a topology template for xcaffold init.
type Template struct {
	render      func(projectName, model string) string
	ID          string
	Label       string
	Description string
}

var registry = []Template{
	{
		ID:          "rest-api",
		Label:       "REST API Service",
		Description: "Backend service exposing data via REST endpoints",
		render:      renderRESTAPI,
	},
	{
		ID:          "cli-tool",
		Label:       "CLI Tool",
		Description: "Command-line tool with subcommands",
		render:      renderCLITool,
	},
	{
		ID:          "frontend-app",
		Label:       "Frontend Application",
		Description: "Web application with component architecture",
		render:      renderFrontendApp,
	},
}

// List returns all available templates.
func List() []Template {
	return registry
}

// Render generates .xcf content for the given template, project name, and model.
func Render(templateID, projectName, model string) (string, error) {
	for _, tmpl := range registry {
		if tmpl.ID == templateID {
			return tmpl.render(projectName, model), nil
		}
	}
	return "", fmt.Errorf("unknown template %q; available: %s", templateID, availableIDs())
}

func availableIDs() string {
	ids := make([]string, len(registry))
	for i, t := range registry {
		ids[i] = t.ID
	}
	return strings.Join(ids, ", ")
}

func renderRESTAPI(projectName, model string) string {
	return fmt.Sprintf(`version: "1.0"
project:
  name: %q
  description: "REST API service"

agents:
  backend:
    description: "Backend developer for API endpoints, database queries, and business logic."
    model: %q
    effort: "high"
    tools: [Bash, Read, Write, Edit, Glob, Grep]
    skills: [api-testing]
    rules: [api-conventions]
    instructions: |
      You are a backend developer.
      Follow RESTful conventions. Write integration tests for every endpoint.
      Use parameterized queries. Never use string interpolation for SQL.

skills:
  api-testing:
    description: "REST API testing patterns"
    instructions: |
      Write integration tests that verify HTTP status codes, response shapes,
      and error handling. Test both success and failure paths.

rules:
  api-conventions:
    description: "REST API design conventions"
    instructions: |
      Use plural nouns for resource endpoints.
      Return appropriate HTTP status codes (201 for creation, 404 for not found).
      Version APIs via URL prefix (/v1/).
    always-apply: true
`, projectName, model)
}

func renderCLITool(projectName, model string) string {
	return fmt.Sprintf(`version: "1.0"
project:
  name: %q
  description: "Command-line tool"

agents:
  developer:
    description: "CLI developer for commands, flags, and user-facing output."
    model: %q
    effort: "high"
    tools: [Bash, Read, Write, Edit, Glob, Grep]
    rules: [cli-conventions]
    instructions: |
      You are a CLI developer.
      Use stdout for output, stderr for errors. Support --help on every command.
      Write unit tests for command logic and integration tests for CLI invocation.

rules:
  cli-conventions:
    description: "CLI design conventions"
    instructions: |
      Use meaningful exit codes (0 success, 1 user error, 2 system error).
      Support --json flag for machine-readable output where applicable.
      Never prompt for input when stdin is not a TTY.
    always-apply: true
`, projectName, model)
}

func renderFrontendApp(projectName, model string) string {
	return fmt.Sprintf(`version: "1.0"
project:
  name: %q
  description: "Frontend web application"

agents:
  frontend:
    description: "Frontend developer for components, pages, and styling."
    model: %q
    effort: "high"
    tools: [Bash, Read, Write, Edit, Glob, Grep]
    skills: [component-testing]
    rules: [frontend-conventions]
    instructions: |
      You are a frontend developer.
      Write accessible, semantic HTML. Use components for reusable UI.
      Write component tests. Never use inline styles for layout.

skills:
  component-testing:
    description: "Component testing patterns"
    instructions: |
      Test components in isolation. Verify render output, user interactions,
      and accessibility attributes. Mock API calls at the network layer.

rules:
  frontend-conventions:
    description: "Frontend coding conventions"
    instructions: |
      Use semantic HTML elements. Ensure all interactive elements are keyboard accessible.
      Keep components focused -- one responsibility per component.
    always-apply: true
`, projectName, model)
}

// RenderProjectXCF generates the kind: project scaffold.xcf content.
// targets is the list of provider names selected by the user.
func RenderProjectXCF(projectName string, targets []string) string {
	var sb strings.Builder

	sb.WriteString("# scaffold.xcf - generated by xcaffold init\n")
	sb.WriteString("# Edit agents/rules/settings in xcf/ then run 'xcaffold apply'.\n")
	sb.WriteString("kind: project\n")
	sb.WriteString("version: \"1.0\"\n")
	sb.WriteString(fmt.Sprintf("name: %q\n", projectName))
	sb.WriteString("\n")
	sb.WriteString("# Compile targets. Add or remove providers as needed.\n")
	sb.WriteString("# Supported: claude, cursor, gemini, antigravity, copilot\n")
	sb.WriteString("targets:\n")
	for _, t := range targets {
		sb.WriteString(fmt.Sprintf("  - %s\n", t))
	}
	sb.WriteString("\n")
	sb.WriteString("# Resources are split into xcf/ subdirectories for readability.\n")
	sb.WriteString("agents:\n  - developer          # xcf/agents/developer.xcf\n")
	sb.WriteString("rules:\n  - conventions        # xcf/rules/conventions.xcf\n")
	sb.WriteString("policies:\n  - safety             # xcf/policies/safety.xcf\n")
	sb.WriteString("\n")
	sb.WriteString("# Uncomment to configure the 'xcaffold test' simulator.\n")
	sb.WriteString("# test:\n")
	sb.WriteString("#   cli-path: \"claude\"\n")
	sb.WriteString("#   judge-model: \"claude-haiku-4-5-20251001\"\n")

	return sb.String()
}

// RenderAgentXCF generates the xcf/agents/developer.xcf content with a
// provider support matrix comment for the given selectedTargets.
func RenderAgentXCF(agentName, model string, selectedTargets []string) string {
	var sb strings.Builder

	matrix := RenderMatrix("agent", selectedTargets)
	if matrix != "" {
		sb.WriteString(matrix)
	}
	sb.WriteString("\n")
	sb.WriteString("kind: agent\n")
	sb.WriteString("version: \"1.0\"\n")
	sb.WriteString(fmt.Sprintf("name: %s\n", agentName))
	sb.WriteString(fmt.Sprintf("description: \"General software developer agent.\"\n"))
	sb.WriteString("\n")
	sb.WriteString("# model: used by claude, gemini, antigravity. Ignored by cursor and copilot.\n")
	sb.WriteString(fmt.Sprintf("model: %q\n", model))
	sb.WriteString("\n")
	sb.WriteString("# effort: claude only. Remove if not targeting claude exclusively.\n")
	sb.WriteString("effort: \"high\"\n")
	sb.WriteString("\n")
	sb.WriteString("tools: [Read, Write, Edit, Bash, Glob, Grep]\n")
	sb.WriteString("\n")
	sb.WriteString("instructions: |\n")
	sb.WriteString("  You are a software developer.\n")
	sb.WriteString("  Write clean, maintainable code.\n")
	sb.WriteString("\n")
	sb.WriteString("# Optional: per-provider instruction overrides\n")
	sb.WriteString("# targets:\n")
	sb.WriteString("#   cursor:\n")
	sb.WriteString("#     instructions-override: |\n")
	sb.WriteString("#       You are a software developer. Keep rules concise.\n")
	sb.WriteString("\n")
	sb.WriteString("# Optional: assertions for 'xcaffold test --judge'\n")
	sb.WriteString("# assertions:\n")
	sb.WriteString("#   - \"The agent must not write files outside the project directory.\"\n")
	sb.WriteString("#   - \"The agent must run tests before marking a task complete.\"\n")

	return sb.String()
}

// RenderRuleXCF generates the xcf/rules/conventions.xcf content.
func RenderRuleXCF(selectedTargets []string) string {
	var sb strings.Builder

	matrix := RenderMatrix("rule", selectedTargets)
	if matrix != "" {
		sb.WriteString(matrix)
	}
	sb.WriteString("\n")
	sb.WriteString("kind: rule\n")
	sb.WriteString("version: \"1.0\"\n")
	sb.WriteString("name: conventions\n")
	sb.WriteString("description: \"Core coding conventions for this project.\"\n")
	sb.WriteString("\n")
	sb.WriteString("# activation: always | path-glob | model-decided | manual-mention | explicit-invoke\n")
	sb.WriteString("activation: always\n")
	sb.WriteString("\n")
	sb.WriteString("instructions: |\n")
	sb.WriteString("  Follow standard coding conventions for this project.\n")
	sb.WriteString("  Write clean, readable, well-documented code.\n")
	sb.WriteString("  Prefer explicit over implicit.\n")
	sb.WriteString("\n")
	sb.WriteString("# Optional: path-scoped activation\n")
	sb.WriteString("# paths:\n")
	sb.WriteString("#   - \"src/**\"\n")
	sb.WriteString("#   - \"lib/**\"\n")

	return sb.String()
}

// RenderSettingsXCF generates the xcf/settings.xcf content.
func RenderSettingsXCF(selectedTargets []string) string {
	var sb strings.Builder

	matrix := RenderMatrix("settings", selectedTargets)
	if matrix != "" {
		sb.WriteString(matrix)
	}
	sb.WriteString("\n")
	sb.WriteString("kind: settings\n")
	sb.WriteString("version: \"1.0\"\n")
	sb.WriteString("\n")
	sb.WriteString("# MCP Servers (claude, cursor, gemini, antigravity)\n")
	sb.WriteString("# Uncomment and configure to register MCP tools.\n")
	sb.WriteString("# mcp-servers:\n")
	sb.WriteString("#   filesystem:\n")
	sb.WriteString("#     type: stdio\n")
	sb.WriteString("#     command: npx\n")
	sb.WriteString("#     args: [\"-y\", \"@modelcontextprotocol/server-filesystem\", \".\"]\n")
	sb.WriteString("\n")
	sb.WriteString("# Permissions (claude only)\n")
	sb.WriteString("# permissions:\n")
	sb.WriteString("#   allow:\n")
	sb.WriteString("#     - \"Bash(npm test *)\"\n")
	sb.WriteString("#   deny:\n")
	sb.WriteString("#     - \"Bash(rm -rf *)\"\n")
	sb.WriteString("\n")
	sb.WriteString("# Hooks (claude only)\n")
	sb.WriteString("# hooks:\n")
	sb.WriteString("#   PreToolUse:\n")
	sb.WriteString("#     - matcher: \"Bash\"\n")
	sb.WriteString("#       hooks:\n")
	sb.WriteString("#         - type: command\n")
	sb.WriteString("#           command: \"echo 'running bash'\"\n")

	return sb.String()
}

// RenderPolicyXCF generates the xcf/policies/safety.xcf content.
// Returns a multi-document YAML string with two starter policies.
func RenderPolicyXCF() string {
	return `# kind: policy - guardrails enforced at 'xcaffold apply' time.
# Both humans and AI assistants filling in this scaffold must comply.
# Violations are caught before any files are written.
kind: policy
version: "1.0"
name: require-agent-description
description: "Every agent must have a description."
severity: warning
target: agent
require:
  - field: description
    is-present: true

---
kind: policy
version: "1.0"
name: require-agent-instructions
description: "Every agent must have instructions."
severity: error
target: agent
require:
  - field: instructions
    min-length: 10
`
}
