package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/saero-ai/xcaffold/internal/ast"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var importCmd = &cobra.Command{
	Use:   "import",
	Short: "Migrate an existing .claude/ directory into scaffold.xcf",
	Long: `xcaffold import scans an existing .claude/ directory and generates
a scaffold.xcf configuration file, allowing you to adopt xcaffold on
existing projects.

┌───────────────────────────────────────────────────────────────────┐
│                          IMPORT PHASE                             │
└───────────────────────────────────────────────────────────────────┘
 • Scans .claude/agents/*.md   → extracts to agents/<id>.md
 • Scans .claude/skills/*/SKILL.md → extracts to skills/<id>/SKILL.md
 • Scans .claude/rules/*.md    → extracts to rules/<id>.md
 • Reads .claude/settings.json for MCP and settings context
 • Generates a scaffold.xcf with instructions_file: references
   (no content is inlined — full fidelity is preserved)

Usage:
  $ xcaffold import`,
	Example: "  $ xcaffold import",
	RunE:    runImport,
}

func init() {
	rootCmd.AddCommand(importCmd)
}

func runImport(cmd *cobra.Command, args []string) error {
	if scopeFlag == scopeGlobal {
		return importScope(globalClaudeDir, globalXcfPath, "global")
	}
	// project (default)
	return importScope(".claude", "scaffold.xcf", "project")
}

// importScope scans a .claude/ directory at claudeDir and writes a xcf file to xcfDest.
func importScope(claudeDir, xcfDest, scopeName string) error {
	if _, err := os.Stat(xcfDest); err == nil {
		return fmt.Errorf("[%s] %s already exists. Remove it first to import", scopeName, xcfDest)
	}

	var extractBase string
	if scopeName == scopeGlobal {
		extractBase = filepath.Join(claudeDir, "imported")
	} else {
		extractBase = "."
	}

	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: ast.ProjectConfig{Name: "imported-project"},
		Agents:  make(map[string]ast.AgentConfig),
		Skills:  make(map[string]ast.SkillConfig),
		Rules:   make(map[string]ast.RuleConfig),
		Hooks:   make(ast.HookConfig),
		MCP:     make(map[string]ast.MCPConfig),
	}

	importCount := 0
	var warnings []string

	if err := extractAgents(claudeDir, extractBase, scopeName, config, &importCount, &warnings); err != nil {
		return err
	}
	if err := extractSkills(claudeDir, extractBase, scopeName, config, &importCount, &warnings); err != nil {
		return err
	}
	if err := extractRules(claudeDir, extractBase, scopeName, config, &importCount, &warnings); err != nil {
		return err
	}

	// 4. Parse settings.json for MCP servers and settings.
	settingsPath := filepath.Join(claudeDir, "settings.json")
	if data, err := os.ReadFile(settingsPath); err == nil {
		if err := importSettings(data, config, &importCount, &warnings); err != nil {
			warnings = append(warnings, fmt.Sprintf("settings.json partially imported: %v", err))
		}
	}

	// Generate scaffolding comment header + YAML.
	header := `# scaffold.xcf — generated by 'xcaffold import'
# Edit this file and run 'xcaffold apply' to manage your agent team.
# Each instructions_file: reference points to an external markdown file.
# Tip: run 'xcaffold graph' to visualize your agent topology.

`
	out, err := yaml.Marshal(config)
	if err != nil {
		return fmt.Errorf("[%s] failed to encode xcf: %w", scopeName, err)
	}

	if err := os.WriteFile(xcfDest, append([]byte(header), out...), 0600); err != nil {
		return fmt.Errorf("[%s] failed to write %s: %w", scopeName, xcfDest, err)
	}

	fmt.Printf("[%s] ✓ Import complete. Created %s with %d resources.\n", scopeName, xcfDest, importCount)
	fmt.Println("  Instructions extracted to external files — full content preserved.")
	fmt.Println("  Run 'xcaffold apply' when ready to assume management.")
	if len(warnings) > 0 {
		fmt.Println("\nWarnings:")
		for _, w := range warnings {
			fmt.Println(" ⚠", w)
		}
	}
	return nil
}

// importSettings parses settings.json and populates MCP, rules, and settings.
func importSettings(data []byte, config *ast.XcaffoldConfig, count *int, warnings *[]string) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	importMCPServers(raw, config, count)
	importStatusAndPlugins(raw, config)

	return nil
}

func importMCPServers(raw map[string]interface{}, config *ast.XcaffoldConfig, count *int) {
	if mcpRaw, ok := raw["mcpServers"].(map[string]interface{}); ok {
		for id, serverRaw := range mcpRaw {
			serverMap, ok := serverRaw.(map[string]interface{})
			if !ok {
				continue
			}
			mc := ast.MCPConfig{}
			if cmdStr, ok := serverMap["command"].(string); ok {
				mc.Command = cmdStr
			}
			if argsRaw, ok := serverMap["args"].([]interface{}); ok {
				for _, a := range argsRaw {
					if argStr, ok := a.(string); ok {
						mc.Args = append(mc.Args, argStr)
					}
				}
			}
			config.MCP[id] = mc
			*count++
		}
	}
}

func importStatusAndPlugins(raw map[string]interface{}, config *ast.XcaffoldConfig) {
	settings := ast.SettingsConfig{}
	changed := false

	if slRaw, ok := raw["statusLine"].(map[string]interface{}); ok {
		settings.StatusLine = &ast.StatusLineConfig{}
		if t, ok := slRaw["type"].(string); ok {
			settings.StatusLine.Type = t
		}
		if c, ok := slRaw["command"].(string); ok {
			settings.StatusLine.Command = c
		}
		changed = true
	}

	if epRaw, ok := raw["enabledPlugins"].(map[string]interface{}); ok {
		settings.EnabledPlugins = make(map[string]bool)
		for k, v := range epRaw {
			if b, ok := v.(bool); ok {
				settings.EnabledPlugins[k] = b
			}
		}
		changed = true
	}

	if el, ok := raw["effortLevel"].(string); ok {
		settings.EffortLevel = el
		changed = true
	}
	if atk, ok := raw["alwaysThinkingEnabled"].(bool); ok {
		settings.AlwaysThinkingEnabled = &atk
		changed = true
	}

	if changed {
		config.Settings = settings
	}
}

func extractAgents(claudeDir, extractBase, scopeName string, config *ast.XcaffoldConfig, count *int, warnings *[]string) error {
	agentFiles, _ := filepath.Glob(filepath.Join(claudeDir, "agents", "*.md"))
	for _, f := range agentFiles {
		data, err := os.ReadFile(f)
		if err != nil {
			*warnings = append(*warnings, fmt.Sprintf("skipping agent %s: %v", f, err))
			continue
		}
		id := strings.TrimSuffix(filepath.Base(f), ".md")
		if id == "" {
			continue
		}
		destPath := filepath.Join(extractBase, "agents", id+".md")
		if err := os.MkdirAll(filepath.Dir(destPath), 0755); err != nil {
			return fmt.Errorf("[%s] failed to create agents/ directory: %w", scopeName, err)
		}
		if err := os.WriteFile(destPath, data, 0600); err != nil {
			return fmt.Errorf("[%s] failed to write %s: %w", scopeName, destPath, err)
		}

		agentCfg := ast.AgentConfig{Description: "Imported agent", InstructionsFile: destPath}
		if fm, ok := extractFrontmatter(data); ok {
			_ = yaml.Unmarshal(fm, &agentCfg)
			// Ensure instructions_file points to the new path regardless of frontmatter
			agentCfg.InstructionsFile = destPath
			agentCfg.Instructions = "" // Avoid conflicts
		}

		config.Agents[id] = agentCfg
		*count++
	}
	return nil
}

func extractSkills(claudeDir, extractBase, scopeName string, config *ast.XcaffoldConfig, count *int, warnings *[]string) error {
	skillFiles, _ := filepath.Glob(filepath.Join(claudeDir, "skills", "*", "SKILL.md"))
	for _, f := range skillFiles {
		data, err := os.ReadFile(f)
		if err != nil {
			*warnings = append(*warnings, fmt.Sprintf("skipping skill %s: %v", f, err))
			continue
		}
		id := filepath.Base(filepath.Dir(f))
		if id == "" || id == "." {
			continue
		}
		destPath := filepath.Join(extractBase, "skills", id, "SKILL.md")
		if err := os.MkdirAll(filepath.Dir(destPath), 0755); err != nil {
			return fmt.Errorf("[%s] failed to create skills/%s/ directory: %w", scopeName, id, err)
		}
		if err := os.WriteFile(destPath, data, 0600); err != nil {
			return fmt.Errorf("[%s] failed to write %s: %w", scopeName, destPath, err)
		}
		refs, err := extractSkillRefs(f, extractBase, scopeName, id, warnings)
		if err != nil {
			return err
		}

		skillCfg := ast.SkillConfig{Description: "Imported skill", InstructionsFile: destPath, References: refs}
		if fm, ok := extractFrontmatter(data); ok {
			_ = yaml.Unmarshal(fm, &skillCfg)
			skillCfg.InstructionsFile = destPath
			skillCfg.Instructions = "" // Avoid conflicts
			if len(refs) > 0 {
				skillCfg.References = append(skillCfg.References, refs...) // merge
			}
		}

		config.Skills[id] = skillCfg
		*count++
	}
	return nil
}

func extractSkillRefs(skillFile, extractBase, scopeName, id string, warnings *[]string) ([]string, error) {
	refSrc := filepath.Join(filepath.Dir(skillFile), "references")
	var refs []string
	if refEntries, err := os.ReadDir(refSrc); err == nil {
		for _, entry := range refEntries {
			if entry.IsDir() {
				continue
			}
			srcRef := filepath.Join(refSrc, entry.Name())
			dstRef := filepath.Join(extractBase, "skills", id, "references", entry.Name())
			if err := os.MkdirAll(filepath.Dir(dstRef), 0755); err != nil {
				return nil, fmt.Errorf("[%s] failed to create references dir: %w", scopeName, err)
			}
			refData, err := os.ReadFile(srcRef)
			if err != nil {
				*warnings = append(*warnings, fmt.Sprintf("skipping reference %s: %v", srcRef, err))
				continue
			}
			if err := os.WriteFile(dstRef, refData, 0600); err != nil {
				return nil, fmt.Errorf("[%s] failed to write reference %s: %w", scopeName, dstRef, err)
			}
			refs = append(refs, dstRef)
		}
	}
	return refs, nil
}

func extractRules(claudeDir, extractBase, scopeName string, config *ast.XcaffoldConfig, count *int, warnings *[]string) error {
	ruleFiles, _ := filepath.Glob(filepath.Join(claudeDir, "rules", "*.md"))
	for _, f := range ruleFiles {
		data, err := os.ReadFile(f)
		if err != nil {
			*warnings = append(*warnings, fmt.Sprintf("skipping rule %s: %v", f, err))
			continue
		}
		id := strings.TrimSuffix(filepath.Base(f), ".md")
		if id == "" {
			continue
		}
		destPath := filepath.Join(extractBase, "rules", id+".md")
		if err := os.MkdirAll(filepath.Dir(destPath), 0755); err != nil {
			return fmt.Errorf("[%s] failed to create rules/ directory: %w", scopeName, err)
		}
		if err := os.WriteFile(destPath, data, 0600); err != nil {
			return fmt.Errorf("[%s] failed to write %s: %w", scopeName, destPath, err)
		}

		ruleCfg := ast.RuleConfig{Description: "Imported rule", InstructionsFile: destPath}
		if fm, ok := extractFrontmatter(data); ok {
			_ = yaml.Unmarshal(fm, &ruleCfg)
			ruleCfg.InstructionsFile = destPath
			ruleCfg.Instructions = "" // Avoid conflicts
		}

		config.Rules[id] = ruleCfg
		*count++
	}
	return nil
}

// extractFrontmatter isolates the YAML section between `---` markers at the start of a markdown file.
func extractFrontmatter(data []byte) ([]byte, bool) {
	if !bytes.HasPrefix(data, []byte("---\n")) && !bytes.HasPrefix(data, []byte("---\r\n")) {
		return nil, false
	}
	// The frontmatter must be closed by another '---'.
	// data[4:] starts after the first '---' block.
	idx := bytes.Index(data[4:], []byte("\n---"))
	if idx == -1 {
		return nil, false
	}
	return data[4 : 4+idx], true
}
