package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/saero-ai/xcaffold/internal/ast"
	"github.com/saero-ai/xcaffold/internal/parser"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestMarshalMultiKind_BasicConfig(t *testing.T) {
	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{Name: "test-project"},
		ResourceScope: ast.ResourceScope{
			Agents: map[string]ast.AgentConfig{
				"developer": {Name: "developer", Description: "Dev", Model: "sonnet"},
			},
			Skills: map[string]ast.SkillConfig{
				"tdd": {Name: "tdd", Description: "TDD"},
			},
			Rules: map[string]ast.RuleConfig{
				"security": {Name: "security", Description: "Security"},
			},
		},
	}

	out, err := MarshalMultiKind(config, "# Generated by test")
	require.NoError(t, err)
	content := string(out)

	// Must have header
	assert.Contains(t, content, "# Generated by test")

	// Must have kind: project document
	assert.Contains(t, content, "kind: project")
	assert.Contains(t, content, "name: test-project")

	// Must have resource kind documents
	assert.Contains(t, content, "kind: agent")
	assert.Contains(t, content, "name: developer")
	assert.Contains(t, content, "kind: skill")
	assert.Contains(t, content, "name: tdd")
	assert.Contains(t, content, "kind: rule")
	assert.Contains(t, content, "name: security")

	// Must have --- separators
	assert.True(t, strings.Count(content, "---") >= 3, "expected at least 3 document separators")

	// Must be parseable by the parser (round-trip)
	parsed, err := parser.Parse(strings.NewReader(content))
	require.NoError(t, err)
	assert.Equal(t, "test-project", parsed.Project.Name)
	assert.Contains(t, parsed.Agents, "developer")
	assert.Contains(t, parsed.Skills, "tdd")
	assert.Contains(t, parsed.Rules, "security")
}

func TestMarshalMultiKind_EmptyResources(t *testing.T) {
	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{Name: "empty-project"},
	}

	out, err := MarshalMultiKind(config, "")
	require.NoError(t, err)
	content := string(out)

	assert.Contains(t, content, "kind: project")
	assert.Contains(t, content, "name: empty-project")
	// No resource documents — no --- separators needed
	assert.NotContains(t, content, "kind: agent")
}

func TestMarshalMultiKind_DeterministicOrder(t *testing.T) {
	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{Name: "order-test"},
		ResourceScope: ast.ResourceScope{
			Agents: map[string]ast.AgentConfig{
				"zulu":  {Name: "zulu", Description: "Last"},
				"alpha": {Name: "alpha", Description: "First"},
			},
		},
	}

	out1, _ := MarshalMultiKind(config, "")
	out2, _ := MarshalMultiKind(config, "")
	assert.Equal(t, string(out1), string(out2), "output must be deterministic")

	// Alpha should appear before Zulu
	content := string(out1)
	alphaIdx := strings.Index(content, "name: alpha")
	zuluIdx := strings.Index(content, "name: zulu")
	assert.Less(t, alphaIdx, zuluIdx, "agents should be sorted alphabetically")
}

func TestMarshalMultiKind_NoHeader(t *testing.T) {
	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{Name: "no-header"},
	}

	out, err := MarshalMultiKind(config, "")
	require.NoError(t, err)
	content := string(out)

	assert.Contains(t, content, "kind: project")
	// No stray leading newlines from empty header
	assert.False(t, strings.HasPrefix(content, "\n"), "no leading newline when header is empty")
}

func TestMarshalMultiKind_WithWorkflowsAndMCP(t *testing.T) {
	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{Name: "full-project"},
		ResourceScope: ast.ResourceScope{
			Workflows: map[string]ast.WorkflowConfig{
				"deploy": {Name: "deploy", Description: "Deployment workflow"},
			},
			MCP: map[string]ast.MCPConfig{
				"github": {Name: "github", Type: "stdio", Command: "gh"},
			},
		},
	}

	out, err := MarshalMultiKind(config, "")
	require.NoError(t, err)
	content := string(out)

	assert.Contains(t, content, "kind: workflow")
	assert.Contains(t, content, "name: deploy")
	assert.Contains(t, content, "kind: mcp")
	assert.Contains(t, content, "name: github")
}

func TestMarshalMultiKind_ExtendsPreserved(t *testing.T) {
	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Extends: "global",
		Project: &ast.ProjectConfig{Name: "extending-project"},
	}

	out, err := MarshalMultiKind(config, "")
	require.NoError(t, err)
	content := string(out)

	assert.Contains(t, content, "extends: global")
}

func TestWriteSplitFiles_DirectoryStructure(t *testing.T) {
	tmpDir := t.TempDir()

	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{
			Name:        "my-project",
			Description: "Test project",
			Targets:     []string{"claude", "antigravity"},
		},
		ResourceScope: ast.ResourceScope{
			Agents: map[string]ast.AgentConfig{
				"developer": {Name: "developer", Description: "Dev agent", Model: "sonnet"},
				"reviewer":  {Name: "reviewer", Description: "Review agent", Model: "haiku"},
			},
			Skills: map[string]ast.SkillConfig{
				"tdd": {Name: "tdd", Description: "Test-driven development"},
			},
			Rules: map[string]ast.RuleConfig{
				"security": {Name: "security", Description: "Security rules"},
			},
			Hooks: ast.HookConfig{
				"PreToolUse": {
					{Hooks: []ast.HookHandler{{Type: "command", Command: "echo pre"}}},
				},
			},
		},
		Settings: ast.SettingsConfig{
			Model: "claude-sonnet-4-5",
		},
	}

	err := WriteSplitFiles(config, tmpDir)
	require.NoError(t, err)

	// scaffold.xcf must exist with kind: project
	scaffoldPath := filepath.Join(tmpDir, "scaffold.xcf")
	assert.FileExists(t, scaffoldPath)
	scaffoldBytes, err := os.ReadFile(scaffoldPath)
	require.NoError(t, err)
	scaffoldContent := string(scaffoldBytes)
	assert.Contains(t, scaffoldContent, "kind: project")
	assert.Contains(t, scaffoldContent, "name: my-project")
	assert.Contains(t, scaffoldContent, "claude")
	assert.Contains(t, scaffoldContent, "antigravity")
	assert.Contains(t, scaffoldContent, "developer")
	assert.Contains(t, scaffoldContent, "reviewer")
	assert.Contains(t, scaffoldContent, "tdd")
	assert.Contains(t, scaffoldContent, "security")

	// Agent files
	assert.FileExists(t, filepath.Join(tmpDir, "xcf", "agents", "developer.xcf"))
	developerBytes, err := os.ReadFile(filepath.Join(tmpDir, "xcf", "agents", "developer.xcf"))
	require.NoError(t, err)
	assert.Contains(t, string(developerBytes), "kind: agent")
	assert.Contains(t, string(developerBytes), "name: developer")

	assert.FileExists(t, filepath.Join(tmpDir, "xcf", "agents", "reviewer.xcf"))

	// Skill file
	assert.FileExists(t, filepath.Join(tmpDir, "xcf", "skills", "tdd.xcf"))
	skillBytes, err := os.ReadFile(filepath.Join(tmpDir, "xcf", "skills", "tdd.xcf"))
	require.NoError(t, err)
	assert.Contains(t, string(skillBytes), "kind: skill")

	// Rule file
	assert.FileExists(t, filepath.Join(tmpDir, "xcf", "rules", "security.xcf"))
	ruleBytes, err := os.ReadFile(filepath.Join(tmpDir, "xcf", "rules", "security.xcf"))
	require.NoError(t, err)
	assert.Contains(t, string(ruleBytes), "kind: rule")

	// Hooks file
	assert.FileExists(t, filepath.Join(tmpDir, "xcf", "hooks.xcf"))
	hooksBytes, err := os.ReadFile(filepath.Join(tmpDir, "xcf", "hooks.xcf"))
	require.NoError(t, err)
	assert.Contains(t, string(hooksBytes), "kind: hooks")
	assert.Contains(t, string(hooksBytes), "events:")

	// Settings file
	assert.FileExists(t, filepath.Join(tmpDir, "xcf", "settings.xcf"))
	settingsBytes, err := os.ReadFile(filepath.Join(tmpDir, "xcf", "settings.xcf"))
	require.NoError(t, err)
	assert.Contains(t, string(settingsBytes), "kind: settings")
}

func TestWriteSplitFiles_RoundTrip(t *testing.T) {
	tmpDir := t.TempDir()

	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{
			Name: "round-trip",
		},
		ResourceScope: ast.ResourceScope{
			Agents: map[string]ast.AgentConfig{
				"alpha": {Name: "alpha", Description: "Alpha agent", Model: "sonnet"},
			},
			Skills: map[string]ast.SkillConfig{
				"deploy": {Name: "deploy", Description: "Deploy skill"},
			},
			Rules: map[string]ast.RuleConfig{
				"lint": {Name: "lint", Description: "Lint rules"},
			},
		},
	}

	err := WriteSplitFiles(config, tmpDir)
	require.NoError(t, err)

	parsed, err := parser.ParseDirectory(tmpDir)
	require.NoError(t, err)

	assert.Equal(t, "round-trip", parsed.Project.Name)
	assert.Contains(t, parsed.Agents, "alpha")
	assert.Contains(t, parsed.Skills, "deploy")
	assert.Contains(t, parsed.Rules, "lint")
}

func TestWriteSplitFiles_Deterministic(t *testing.T) {
	tmpDir1 := t.TempDir()
	tmpDir2 := t.TempDir()

	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{
			Name:    "deterministic",
			Targets: []string{"claude"},
		},
		ResourceScope: ast.ResourceScope{
			Agents: map[string]ast.AgentConfig{
				"zulu":  {Name: "zulu", Model: "sonnet"},
				"alpha": {Name: "alpha", Model: "haiku"},
			},
			Skills: map[string]ast.SkillConfig{
				"skill-b": {Name: "skill-b"},
				"skill-a": {Name: "skill-a"},
			},
		},
	}

	err := WriteSplitFiles(config, tmpDir1)
	require.NoError(t, err)
	err = WriteSplitFiles(config, tmpDir2)
	require.NoError(t, err)

	// Compare scaffold.xcf
	b1, err := os.ReadFile(filepath.Join(tmpDir1, "scaffold.xcf"))
	require.NoError(t, err)
	b2, err := os.ReadFile(filepath.Join(tmpDir2, "scaffold.xcf"))
	require.NoError(t, err)
	assert.Equal(t, b1, b2, "scaffold.xcf must be byte-identical")

	// Compare an agent file
	a1, err := os.ReadFile(filepath.Join(tmpDir1, "xcf", "agents", "alpha.xcf"))
	require.NoError(t, err)
	a2, err := os.ReadFile(filepath.Join(tmpDir2, "xcf", "agents", "alpha.xcf"))
	require.NoError(t, err)
	assert.Equal(t, a1, a2, "agent file must be byte-identical")
}

func TestWriteSplitFiles_EmptyResources(t *testing.T) {
	tmpDir := t.TempDir()

	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{
			Name: "empty-project",
		},
	}

	err := WriteSplitFiles(config, tmpDir)
	require.NoError(t, err)

	// scaffold.xcf must be created
	assert.FileExists(t, filepath.Join(tmpDir, "scaffold.xcf"))

	// No xcf/agents/ directory when there are no agents
	_, statErr := os.Stat(filepath.Join(tmpDir, "xcf", "agents"))
	assert.True(t, os.IsNotExist(statErr), "xcf/agents/ should not exist when config has no agents")
}

func TestWriteSplitFiles_NoHooks_NoHooksFile(t *testing.T) {
	tmpDir := t.TempDir()

	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{
			Name: "no-hooks",
		},
		ResourceScope: ast.ResourceScope{
			Agents: map[string]ast.AgentConfig{
				"agent1": {Name: "agent1", Model: "sonnet"},
			},
		},
	}

	err := WriteSplitFiles(config, tmpDir)
	require.NoError(t, err)

	_, statErr := os.Stat(filepath.Join(tmpDir, "xcf", "hooks.xcf"))
	assert.True(t, os.IsNotExist(statErr), "xcf/hooks.xcf should not be created when config has no hooks")
}
