package main

import (
	"strings"
	"testing"

	"github.com/saero-ai/xcaffold/internal/ast"
	"github.com/saero-ai/xcaffold/internal/parser"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestMarshalMultiKind_BasicConfig(t *testing.T) {
	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{Name: "test-project"},
		ResourceScope: ast.ResourceScope{
			Agents: map[string]ast.AgentConfig{
				"developer": {Name: "developer", Description: "Dev", Model: "sonnet"},
			},
			Skills: map[string]ast.SkillConfig{
				"tdd": {Name: "tdd", Description: "TDD"},
			},
			Rules: map[string]ast.RuleConfig{
				"security": {Name: "security", Description: "Security"},
			},
		},
	}

	out, err := MarshalMultiKind(config, "# Generated by test")
	require.NoError(t, err)
	content := string(out)

	// Must have header
	assert.Contains(t, content, "# Generated by test")

	// Must have kind: config document
	assert.Contains(t, content, "kind: config")
	assert.Contains(t, content, "name: test-project")

	// Must have resource kind documents
	assert.Contains(t, content, "kind: agent")
	assert.Contains(t, content, "name: developer")
	assert.Contains(t, content, "kind: skill")
	assert.Contains(t, content, "name: tdd")
	assert.Contains(t, content, "kind: rule")
	assert.Contains(t, content, "name: security")

	// Must have --- separators
	assert.True(t, strings.Count(content, "---") >= 3, "expected at least 3 document separators")

	// Must be parseable by the parser (round-trip)
	parsed, err := parser.Parse(strings.NewReader(content))
	require.NoError(t, err)
	assert.Equal(t, "test-project", parsed.Project.Name)
	assert.Contains(t, parsed.Agents, "developer")
	assert.Contains(t, parsed.Skills, "tdd")
	assert.Contains(t, parsed.Rules, "security")
}

func TestMarshalMultiKind_EmptyResources(t *testing.T) {
	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{Name: "empty-project"},
	}

	out, err := MarshalMultiKind(config, "")
	require.NoError(t, err)
	content := string(out)

	assert.Contains(t, content, "kind: config")
	assert.Contains(t, content, "name: empty-project")
	// No resource documents — no --- separators needed
	assert.NotContains(t, content, "kind: agent")
}

func TestMarshalMultiKind_DeterministicOrder(t *testing.T) {
	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{Name: "order-test"},
		ResourceScope: ast.ResourceScope{
			Agents: map[string]ast.AgentConfig{
				"zulu":  {Name: "zulu", Description: "Last"},
				"alpha": {Name: "alpha", Description: "First"},
			},
		},
	}

	out1, _ := MarshalMultiKind(config, "")
	out2, _ := MarshalMultiKind(config, "")
	assert.Equal(t, string(out1), string(out2), "output must be deterministic")

	// Alpha should appear before Zulu
	content := string(out1)
	alphaIdx := strings.Index(content, "name: alpha")
	zuluIdx := strings.Index(content, "name: zulu")
	assert.Less(t, alphaIdx, zuluIdx, "agents should be sorted alphabetically")
}

func TestMarshalMultiKind_NoHeader(t *testing.T) {
	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{Name: "no-header"},
	}

	out, err := MarshalMultiKind(config, "")
	require.NoError(t, err)
	content := string(out)

	assert.Contains(t, content, "kind: config")
	// No stray leading newlines from empty header
	assert.False(t, strings.HasPrefix(content, "\n"), "no leading newline when header is empty")
}

func TestMarshalMultiKind_WithWorkflowsAndMCP(t *testing.T) {
	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Project: &ast.ProjectConfig{Name: "full-project"},
		ResourceScope: ast.ResourceScope{
			Workflows: map[string]ast.WorkflowConfig{
				"deploy": {Name: "deploy", Description: "Deployment workflow"},
			},
			MCP: map[string]ast.MCPConfig{
				"github": {Name: "github", Type: "stdio", Command: "gh"},
			},
		},
	}

	out, err := MarshalMultiKind(config, "")
	require.NoError(t, err)
	content := string(out)

	assert.Contains(t, content, "kind: workflow")
	assert.Contains(t, content, "name: deploy")
	assert.Contains(t, content, "kind: mcp")
	assert.Contains(t, content, "name: github")
}

func TestMarshalMultiKind_ExtendsPreserved(t *testing.T) {
	config := &ast.XcaffoldConfig{
		Version: "1.0",
		Extends: "global",
		Project: &ast.ProjectConfig{Name: "extending-project"},
	}

	out, err := MarshalMultiKind(config, "")
	require.NoError(t, err)
	content := string(out)

	assert.Contains(t, content, "extends: global")
}
